/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generator

import (
	"bytes"
	"context"
	"encoding/json"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"maps"
	"path/filepath"
	"slices"
	"strings"
	"sync"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gobuffalo/flect"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
	"github.com/spf13/afero"
	"golang.org/x/tools/go/ast/astutil"
	extv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/kube-openapi/pkg/spec3"
	"k8s.io/kube-openapi/pkg/validation/spec"
	"sigs.k8s.io/yaml"

	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"

	xpv1 "github.com/crossplane/crossplane/apis/v2/apiextensions/v1"

	"github.com/crossplane/cli/v2/internal/crd"
	"github.com/crossplane/cli/v2/internal/schemas/runner"
)

// K8s package constants.
const (
	k8sPkgMetaV1        = "io.k8s.apimachinery.pkg.apis.meta.v1"
	k8sPkgRuntime       = "io.k8s.apimachinery.pkg.runtime"
	k8sPkgCoreV1        = "io.k8s.api.core.v1"
	k8sPkgIntStr        = "io.k8s.apimachinery.pkg.util.intstr"
	k8sPkgResource      = "io.k8s.apimachinery.pkg.api.resource"
	k8sPkgAutoscalingV1 = "io.k8s.api.autoscaling.v1"

	k8sPkgNameAutoscaling = "autoscaling"
)

// goModContents is the contents of the go.mod we write for our generated models
// module. All generated models share the same module so that we can generate a
// single dependency from embedded Go functions. We always resolve this
// dependency via a replace statement, so `dev.crossplane.io/models` is never
// actually used as a URL, just an identifier.
const goModContents = `module dev.crossplane.io/models

go 1.23

require github.com/oapi-codegen/runtime v1.1.0

require (
	github.com/apapsch/go-jsonmerge/v2 v2.0.0 // indirect
	github.com/google/uuid v1.4.0 // indirect
)
`

// goSumContents is the contents of the go.sum we write for our generated models
// module alongside the go.mod.
const goSumContents = `github.com/RaveNoX/go-jsoncommentstrip v1.0.0/go.mod h1:78ihd09MekBnJnxpICcwzCMzGrKSKYe4AqU6PDYYpjk=
github.com/apapsch/go-jsonmerge/v2 v2.0.0 h1:axGnT1gRIfimI7gJifB699GoE/oq+F2MU7Dml6nw9rQ=
github.com/apapsch/go-jsonmerge/v2 v2.0.0/go.mod h1:lvDnEdqiQrp0O42VQGgmlKpxL1AP2+08jFMw88y4klk=
github.com/bmatcuk/doublestar v1.1.1/go.mod h1:UD6OnuiIn0yFxxA2le/rnRU1G4RaI4UvFv1sNto9p6w=
github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/google/uuid v1.4.0 h1:MtMxsa51/r9yyhkyLsVeVt0B+BGQZzpQiTQ4eHZ8bc4=
github.com/google/uuid v1.4.0/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
github.com/juju/gnuflag v0.0.0-20171113085948-2ce1bb71843d/go.mod h1:2PavIy+JPciBPrBUjwbNvtwB6RQlve+hkpll6QSNmOE=
github.com/oapi-codegen/runtime v1.1.0 h1:rJpoNUawn5XTvekgfkvSZr0RqEnoYpFkyvrzfWeFKWM=
github.com/oapi-codegen/runtime v1.1.0/go.mod h1:BeSfBkWWWnAnGdyS+S/GnlbmHKzf8/hwkvelJZDeKA8=
github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/spkg/bom v0.0.0-20160624110644-59b7046e48ad/go.mod h1:qLr4V1qq6nMqFKkMo8ZTx3f+BZEkzsRUY10Xsm2mwU0=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/testify v1.3.0/go.mod h1:M5WIy9Dh21IEIfnGCwXGc5bZfKNJtfHm1UVUgZn+9EI=
github.com/stretchr/testify v1.8.4 h1:CcVxjf3Q8PM0mHUKJCdn+eZZtm5yQwehR5yeSVQQcUk=
github.com/stretchr/testify v1.8.4/go.mod h1:sz/lmYIOXD/1dqDmKjjqLyZ2RngseejIcXlSw2iwfAo=
gopkg.in/yaml.v3 v3.0.1 h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
gopkg.in/yaml.v3 v3.0.1/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
`

// goImportsTemplate replaces the default import template for oapi-codegen,
// since it contains many imports we don't use and will thus result in code that
// doesn't compile.
const goImportsTemplate = `// Package {{.PackageName}} contains generated models.
//
// Code generated by {{.ModuleName}} version {{.Version}} DO NOT EDIT.
package {{.PackageName}}

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"

	{{- range .ExternalImports}}
	{{ . }}
	{{- end}}
	{{- range .AdditionalImports}}
	{{.Alias}} "{{.Package}}"
	{{- end}}
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_ = fmt.Errorf
	_ = runtime.JSONMerge
)
`

type goGenerator struct{}

func (goGenerator) Language() string {
	return "go"
}

// GenerateFromCRD generates Go schemas for the CRDs in the given filesystem.
func (goGenerator) GenerateFromCRD(_ context.Context, fromFS afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	openAPIs, err := goCollectOpenAPIs(fromFS)
	if err != nil {
		return nil, err
	}

	if len(openAPIs) == 0 {
		// Return nil if no specs were generated
		return nil, nil
	}

	// Initialize the schema filesystem
	schemaFS, err := initializeSchemaFS()
	if err != nil {
		return nil, err
	}

	// Extract shared k8s schemas and generate separate files for each package.
	// We have to do this before generating the other models below because
	// the code below replaces the k8s models with references to these shared
	// ones in-place in the spec.
	k8sSchemasByPackage := make(map[string]map[string]*spec.Schema)

	// Collect all K8s schemas from all OpenAPI specs, grouped by package
	for _, oapi := range openAPIs {
		packagedSchemas := goExtractK8sSchemas(oapi.spec)
		for pkg, schemas := range packagedSchemas {
			if k8sSchemasByPackage[pkg] == nil {
				k8sSchemasByPackage[pkg] = make(map[string]*spec.Schema)
			}
			maps.Copy(k8sSchemasByPackage[pkg], schemas)
		}
	}

	// Generate separate files for each K8s package
	for pkg, schemas := range k8sSchemasByPackage {
		if len(schemas) == 0 {
			continue
		}

		// Create a spec for this package
		pkgSpec := &spec3.OpenAPI{
			Version: "3.0.0",
			Components: &spec3.Components{
				Schemas: schemas,
			},
		}

		// Determine the group, kind, and version from the package name
		var group, kind, version string
		switch pkg {
		case k8sPkgMetaV1:
			group = "meta.k8s.io"
			kind = "meta"
			version = "v1"
		case k8sPkgAutoscalingV1:
			group = k8sPkgNameAutoscaling
			kind = k8sPkgNameAutoscaling
			version = "v1"
		}

		// For K8s packages that reference meta.v1, we need to use the correct
		// meta import path. The meta.v1 package uses goReferenceK8sTypes (core
		// path) because self-references get stripped. Other packages like
		// autoscaling use goReferenceK8sTypesForCRDs (non-core path) to
		// reference the CRD meta.v1 package at
		// dev.crossplane.io/models/io/k8s/meta/v1.
		refMutator := goReferenceK8sTypes
		if pkg != k8sPkgMetaV1 {
			refMutator = goReferenceK8sTypesForCRDs
		}

		code, err := generateGo(pkgSpec, version,
			goRenameTypes,
			goRenameEnums,
			goReplaceNumberWithInt,
			goRemoveRequired,
			refMutator,
		)
		if err != nil {
			return nil, err
		}

		// shorten the auto‑generated K8s type names
		code, err = fixK8sTypeNames(code)
		if err != nil {
			return nil, err
		}

		// remove the self‑import (e.g. meta/v1 importing itself)
		code, err = removeSelfImports(code, pkg)
		if err != nil {
			return nil, err
		}

		if err := writeGoCode(schemaFS, group, kind, version, code); err != nil {
			return nil, err
		}
	}

	// Generate models for the non-k8s schemas.
	for _, oapi := range openAPIs {
		code, err := generateGo(oapi.spec, oapi.version,
			goRenameTypes,
			goRenameEnums,
			goReplaceNumberWithInt,
			goRemoveRequired,
			goReferenceK8sTypesForCRDs,
			goRemoveK8s,
			goKeepOnlyComponents,
		)
		if err != nil {
			return nil, err
		}

		if err := writeGoCode(schemaFS, oapi.crd.Spec.Group, oapi.crd.Spec.Names.Kind, oapi.version, code); err != nil {
			return nil, err
		}
	}

	return schemaFS, nil
}

type goOpenAPI struct {
	crd     *extv1.CustomResourceDefinition
	version string
	spec    *spec3.OpenAPI
}

func goCollectOpenAPIs(fromFS afero.Fs) ([]goOpenAPI, error) { //nolint:gocognit // Hard to split this up, and it's not too long to read.
	crdFS := afero.NewMemMapFs()
	baseFolder := "workdir"

	if err := crdFS.MkdirAll(baseFolder, 0o755); err != nil {
		return nil, err
	}

	var openAPIs []goOpenAPI
	return openAPIs, afero.Walk(fromFS, "", func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}
		// Ignore files without yaml extensions.
		ext := filepath.Ext(path)
		if ext != ".yaml" && ext != ".yml" {
			return nil
		}

		var u metav1.TypeMeta
		bs, err := afero.ReadFile(fromFS, path)
		if err != nil {
			return errors.Wrapf(err, "failed to read file %q", path)
		}
		err = yaml.Unmarshal(bs, &u)
		if err != nil {
			return errors.Wrapf(err, "failed to parse file %q", path)
		}

		switch u.GroupVersionKind().Kind {
		case xpv1.CompositeResourceDefinitionKind:
			// Process the XRD and get the paths
			xrPath, claimPath, err := crd.ProcessXRD(crdFS, bs, path, baseFolder)
			if err != nil {
				return err
			}

			if xrPath != "" {
				bs, err := afero.ReadFile(crdFS, xrPath)
				if err != nil {
					return errors.Wrapf(err, "failed to read file %q", xrPath)
				}

				var c extv1.CustomResourceDefinition
				if err := yaml.Unmarshal(bs, &c); err != nil {
					return errors.Wrapf(err, "failed to unmarshal CRD file %q", xrPath)
				}

				oapis, err := crd.ToOpenAPI(&c)
				if err != nil {
					return err
				}
				for version, oapi := range oapis {
					openAPIs = append(openAPIs, goOpenAPI{spec: oapi, version: version, crd: &c})
				}
			}
			if claimPath != "" {
				bs, err := afero.ReadFile(crdFS, claimPath)
				if err != nil {
					return errors.Wrapf(err, "failed to read file %q", claimPath)
				}

				var c extv1.CustomResourceDefinition
				if err := yaml.Unmarshal(bs, &c); err != nil {
					return errors.Wrapf(err, "failed to unmarshal CRD file %q", claimPath)
				}

				oapis, err := crd.ToOpenAPI(&c)
				if err != nil {
					return err
				}
				for version, oapi := range oapis {
					openAPIs = append(openAPIs, goOpenAPI{spec: oapi, version: version, crd: &c})
				}
			}

		case "CustomResourceDefinition":
			var c extv1.CustomResourceDefinition
			if err := yaml.Unmarshal(bs, &c); err != nil {
				return errors.Wrapf(err, "failed to unmarshal CRD file %q", path)
			}

			oapis, err := crd.ToOpenAPI(&c)
			if err != nil {
				return err
			}
			for version, oapi := range oapis {
				openAPIs = append(openAPIs, goOpenAPI{spec: oapi, version: version, crd: &c})
			}
		}
		return nil
	})
}

// generateGoMutex prevents concurrent calls to `codegen.Generate` in
// `generateGo`, since `codegen.Generate` is not concurrency safe.
var generateGoMutex sync.Mutex //nolint:gochecknoglobals // Must be global.

func generateGo(s *spec3.OpenAPI, version string, mutators ...func(*spec3.OpenAPI)) (string, error) {
	for _, mut := range mutators {
		mut(s)
	}

	// Round-trip through JSON to convert the spec to the kin library used by
	// oapi-codegen.
	bs, err := json.Marshal(s)
	if err != nil {
		return "", errors.Wrap(err, "failed to marshal OpenAPI spec")
	}
	ld := openapi3.NewLoader()
	oapiInput, err := ld.LoadFromData(bs)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse OpenAPI spec")
	}

	// Generate code!
	generateGoMutex.Lock()
	defer generateGoMutex.Unlock()
	goCode, err := codegen.Generate(oapiInput, codegen.Configuration{
		PackageName: version,
		Generate: codegen.GenerateOptions{
			Models: true,
		},
		OutputOptions: codegen.OutputOptions{
			SkipPrune:      true,
			NameNormalizer: string(codegen.NameNormalizerFunctionToCamelCaseWithInitialisms),
			SkipFmt:        true,
			UserTemplates: map[string]string{
				"imports.tmpl": goImportsTemplate,
			},
		},
	})
	if err != nil {
		return "", errors.Wrap(err, "failed to generate go code from OpenAPI schema")
	}

	// Post-process to fix missing imports for map value types
	goCode, err = fixMissingImports(goCode)
	if err != nil {
		return "", errors.Wrap(err, "failed to fix missing imports")
	}

	goCodeBytes, err := format.Source([]byte(goCode))
	if err != nil {
		return "", errors.Wrap(err, "failed to format go code")
	}

	return string(goCodeBytes), nil
}

// goExtractK8sSchemas returns all k8s schemas from the given OpenAPI
// spec, grouped by their package.
func goExtractK8sSchemas(s *spec3.OpenAPI) map[string]map[string]*spec.Schema {
	ret := make(map[string]map[string]*spec.Schema)

	// Define the K8s packages we want to extract
	k8sPackages := []string{
		k8sPkgMetaV1,
		k8sPkgRuntime,
		k8sPkgCoreV1,
		k8sPkgIntStr,
		k8sPkgResource,
		k8sPkgAutoscalingV1,
	}

	// Initialize the map for each package
	for _, pkg := range k8sPackages {
		ret[pkg] = make(map[string]*spec.Schema)
	}

	// Group schemas by their package
	for name, schema := range s.Components.Schemas {
		for _, pkg := range k8sPackages {
			if strings.Contains(name, pkg) {
				ret[pkg][name] = schema
				break
			}
		}
	}

	// Remove empty groups
	for pkg := range ret {
		if len(ret[pkg]) == 0 {
			delete(ret, pkg)
		}
	}

	return ret
}

func writeGoCode(schemaFS afero.Fs, group, kind, version, code string) error {
	goPath := filepath.Join("models", goSchemaPath(group, kind, version))
	dir := filepath.Dir(goPath)
	if err := schemaFS.MkdirAll(dir, 0o755); err != nil {
		return errors.Wrap(err, "failed to create directory for schemas")
	}

	f, err := schemaFS.Create(goPath)
	if err != nil {
		return errors.Wrap(err, "failed to create go schema file")
	}
	if _, err := f.WriteString(code); err != nil {
		return errors.Wrap(err, "failed to write go code to file")
	}
	_ = f.Close()

	return nil
}

func goSchemaPath(group, kind, version string) string {
	// Our Go files will live in directories based on the CRD group and
	// version. The filename is the singular kind of the CRD.
	//
	// Example: Kind "Bucket" in group "platform.example.com/v1alpha1" becomes
	// com/example/platform/v1alpha1/bucket.go.
	// Special case: meta.core.k8s.io becomes io/k8s/core/meta/v1 for built-in K8s types
	if group == "meta.core.k8s.io" {
		return filepath.Join("io", "k8s", "core", "meta", version, strings.ToLower(kind)+".go")
	}

	// Handle specific K8s groups that should be under io/k8s/
	switch group {
	case "apps", k8sPkgNameAutoscaling, "batch", "policy":
		return filepath.Join("io", "k8s", group, version, strings.ToLower(kind)+".go")
	}

	path := strings.Split(group, ".")
	slices.Reverse(path)
	path = append(path, version, strings.ToLower(kind)+".go")

	return filepath.Join(path...)
}

// goRenameTypes adds annotations to schemas to cause oapi-codegen to generate
// nice type names.
func goRenameTypes(s *spec3.OpenAPI) {
	for name, schema := range s.Components.Schemas {
		goName := goFixName(name)
		if goName == "" {
			delete(s.Components.Schemas, name)
			continue
		}
		goRenameSchemaType(goName, schema)
		goRenamePropertyTypes(goName, schema.Properties)
	}
}

func goRenamePropertyTypes(baseName string, props map[string]spec.Schema) {
	for name, prop := range props {
		goName := goFixName(baseName + flect.Capitalize(name))

		goRenameSchemaType(goName, &prop)
		goRenamePropertyTypes(goName, prop.Properties)

		if prop.Items != nil {
			goRenameSchemaType(goName+"Item", prop.Items.Schema)
			goRenamePropertyTypes(goName+"Item", prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

func goFixName(name string) string {
	generateGoMutex.Lock()
	defer generateGoMutex.Unlock()

	lastDot := strings.LastIndex(name, ".")
	if lastDot == -1 {
		return codegen.ToCamelCaseWithInitialisms(name)
	}
	genName := codegen.SchemaNameToTypeName(name)
	prefix := codegen.SchemaNameToTypeName(name[:lastDot])
	return codegen.ToCamelCaseWithInitialisms(strings.TrimPrefix(genName, prefix))
}

func goRenameSchemaType(name string, schema *spec.Schema) {
	schema.AddExtension("x-go-type-name", name)
	schema.AddExtension("x-oapi-codegen-only-honour-go-name", true)
}

// goRenameEnums names enum values unambiguously so different generated models
// can live in the same package.
func goRenameEnums(s *spec3.OpenAPI) {
	for name, schema := range s.Components.Schemas {
		goName := goFixName(name)
		if goName == "" {
			delete(s.Components.Schemas, name)
			continue
		}
		goRenameEnumValues(goName, schema)
		goRenamePropertyEnums(goName, schema.Properties)
	}
}

func goRenamePropertyEnums(baseName string, props map[string]spec.Schema) {
	for name, prop := range props {
		goName := goFixName(baseName + flect.Capitalize(name))

		goRenameEnumValues(goName, &prop)
		goRenamePropertyEnums(goName, prop.Properties)

		if prop.Items != nil {
			goRenameEnumValues(goName+"Item", prop.Items.Schema)
			goRenamePropertyEnums(goName+"Item", prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

func goRenameEnumValues(typeName string, schema *spec.Schema) {
	if schema.Enum == nil {
		return
	}

	newNames := make([]string, len(schema.Enum))
	for i, oldName := range schema.Enum {
		s, ok := oldName.(string)
		if !ok {
			// This should always be true, but we'd rather not panic, so ignore
			// any non-string enums.
			continue
		}
		newNames[i] = typeName + flect.Capitalize(s)
	}

	schema.AddExtension("x-enum-varnames", newNames)
}

// goReplaceNumberWithInt adds annotations to schemas to cause oapi-codegen to
// generate int type fields instead of floats for numbers.
func goReplaceNumberWithInt(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		goRetypeSchema(schema, "number", "int")
		goRetypeProperties(schema.Properties, "number", "int")
	}
}

func goRetypeProperties(props map[string]spec.Schema, oldType, newType string) {
	for name, prop := range props {
		goRetypeSchema(&prop, oldType, newType)
		if prop.Items != nil {
			goRetypeSchema(prop.Items.Schema, oldType, newType)
			goRetypeProperties(prop.Items.Schema.Properties, oldType, newType)
		}
		props[name] = prop
	}
}

func goRetypeSchema(schema *spec.Schema, oldType, newType string) {
	if schema.Type.Contains(oldType) {
		schema.AddExtension("x-go-type", newType)
	}
}

// goRemoveRequired removes the required fields from schemas. We want all fields
// in our generated models to be optional (so functions can set only the fields
// they wish to own).
func goRemoveRequired(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		schema.Required = nil
		goRemovePropertiesRequired(schema.Properties)
		if schema.Items != nil {
			goRemovePropertiesRequired(schema.Items.Schema.Properties)
		}
	}
}

func goRemovePropertiesRequired(props map[string]spec.Schema) {
	for name, prop := range props {
		prop.Required = nil
		goRemovePropertiesRequired(prop.Properties)
		if prop.Items != nil {
			prop.Items.Schema.Required = nil
			goRemovePropertiesRequired(prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

// goReferenceK8sTypes converts all references to k8s meta/v1 schemas in the
// given spec to references to the shared Go models we generate for the k8s
// schemas.
func goReferenceK8sTypes(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		goReferenceK8sType(schema)
		goReferenceK8sTypesProperties(schema.Properties)
	}
}

// goReferenceK8sTypesForCRDs is like goReferenceK8sTypes but uses different
// import paths appropriate for CRDs. For CRDs, we only need to handle meta.v1
// differently since CRDs might use meta.k8s.io group.
func goReferenceK8sTypesForCRDs(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		goReferenceK8sTypeWithMetaPath(schema, false)
		goReferenceK8sTypesPropertiesWithMetaPath(schema.Properties, false)
	}
}

func goReferenceK8sType(schema *spec.Schema) {
	goReferenceK8sTypeWithMetaPath(schema, true)
}

func goReferenceK8sTypeWithMetaPath(schema *spec.Schema, useCorePath bool) {
	// Helper function to check if a reference is a k8s type
	isK8sRef := func(ref string) bool {
		return strings.Contains(ref, k8sPkgMetaV1) ||
			strings.Contains(ref, k8sPkgCoreV1) ||
			strings.Contains(ref, k8sPkgRuntime) ||
			strings.Contains(ref, k8sPkgIntStr) ||
			strings.Contains(ref, k8sPkgResource) ||
			strings.Contains(ref, k8sPkgAutoscalingV1)
	}

	// Handle direct reference
	ref := schema.Ref.String()
	if isK8sRef(ref) {
		tryReplaceK8sTypeWithMetaPath(schema, ref, useCorePath)
		// Clear the original reference after replacement
		schema.Ref = spec.Ref{}
	}

	// Handle AllOf - if all schemas in AllOf are k8s refs, we can replace the whole schema
	allK8s := true
	for _, one := range schema.AllOf {
		if one.Ref.String() == "" || !isK8sRef(one.Ref.String()) {
			allK8s = false
			break
		}
	}

	if allK8s && len(schema.AllOf) > 0 {
		// Use the first AllOf ref for the replacement
		ref := schema.AllOf[0].Ref.String()
		tryReplaceK8sTypeWithMetaPath(schema, ref, useCorePath)
		schema.AllOf = nil
	} else {
		// Process each AllOf individually
		for i := range schema.AllOf {
			goReferenceK8sTypeWithMetaPath(&schema.AllOf[i], useCorePath)
		}
	}

	// Also check OneOf and AnyOf
	for i := range schema.OneOf {
		goReferenceK8sTypeWithMetaPath(&schema.OneOf[i], useCorePath)
	}
	for i := range schema.AnyOf {
		goReferenceK8sTypeWithMetaPath(&schema.AnyOf[i], useCorePath)
	}
}

func goReferenceK8sTypesProperties(props map[string]spec.Schema) {
	goReferenceK8sTypesPropertiesWithMetaPath(props, true)
}

func goReferenceK8sTypesPropertiesWithMetaPath(props map[string]spec.Schema, useCorePath bool) {
	for name, prop := range props {
		goReferenceK8sTypeWithMetaPath(&prop, useCorePath)
		goReferenceK8sTypesPropertiesWithMetaPath(prop.Properties, useCorePath)
		if prop.Items != nil {
			goReferenceK8sTypeWithMetaPath(prop.Items.Schema, useCorePath)
			goReferenceK8sTypesPropertiesWithMetaPath(prop.Items.Schema.Properties, useCorePath)
		}
		if prop.AdditionalProperties != nil && prop.AdditionalProperties.Schema != nil {
			goReferenceK8sTypeWithMetaPath(prop.AdditionalProperties.Schema, useCorePath)
			goReferenceK8sTypesPropertiesWithMetaPath(prop.AdditionalProperties.Schema.Properties, useCorePath)
		}

		props[name] = prop
	}
}

func tryReplaceK8sTypeWithMetaPath(schema *spec.Schema, ref string, useCorePath bool) {
	lastDot := strings.LastIndex(ref, ".")
	if lastDot == -1 {
		return
	}
	t := ref[lastDot+1:]

	// Determine the correct alias and path for meta.v1
	metaAlias := "metacorev1"
	metaPath := "dev.crossplane.io/models/io/k8s/core/meta/v1"
	if !useCorePath {
		metaAlias = "metav1"
		metaPath = "dev.crossplane.io/models/io/k8s/meta/v1"
	}

	mapping := []struct {
		contains   string
		alias      string
		importPath string
	}{
		{
			contains:   k8sPkgMetaV1,
			alias:      metaAlias,
			importPath: metaPath,
		},
		{
			contains:   k8sPkgCoreV1,
			alias:      "corev1",
			importPath: "dev.crossplane.io/models/io/k8s/core/v1",
		},
		{
			contains:   k8sPkgRuntime,
			alias:      "runtimev1",
			importPath: "dev.crossplane.io/models/io/k8s/runtime/v1",
		},
		{
			contains:   k8sPkgIntStr,
			alias:      "intstrv1",
			importPath: "dev.crossplane.io/models/io/k8s/util/v1",
		},
		{
			contains:   k8sPkgResource,
			alias:      "resourcev1",
			importPath: "dev.crossplane.io/models/io/k8s/resource/v1",
		},
		{
			contains:   k8sPkgAutoscalingV1,
			alias:      "autoscalingv1",
			importPath: "dev.crossplane.io/models/io/k8s/autoscaling/v1",
		},
	}

	for _, m := range mapping {
		if strings.Contains(ref, m.contains) {
			schema.AddExtension("x-go-type", m.alias+"."+t)
			schema.AddExtension("x-go-type-import", map[string]string{
				"path": m.importPath,
				"name": m.alias,
			})
			return
		}
	}
}

// goRemoveK8s removes all k8s schemas from the given OpenAPI spec, so
// that we can generate models for them separately and share them across all our
// other generated models.
func goRemoveK8s(s *spec3.OpenAPI) {
	for name := range s.Components.Schemas {
		if strings.HasPrefix(name, k8sPkgMetaV1) ||
			strings.HasPrefix(name, k8sPkgRuntime) ||
			strings.HasPrefix(name, k8sPkgCoreV1) ||
			strings.HasPrefix(name, k8sPkgIntStr) ||
			strings.HasPrefix(name, k8sPkgResource) ||
			strings.HasPrefix(name, k8sPkgAutoscalingV1) {
			delete(s.Components.Schemas, name)
		}
	}
}

// goKeepOnlyComponents leaves only the "components" portion of the OpenAPI spec
// in place. This lets us make oapi-codegen generate code only for schemas and
// not a full REST client.
func goKeepOnlyComponents(s *spec3.OpenAPI) {
	*s = spec3.OpenAPI{
		Version:    s.Version,
		Info:       s.Info,
		Components: s.Components,
	}
}

// goAddDefaults adds default values for apiVersion and kind properties based on
// x-kubernetes-group-version-kind extension.
func goAddDefaults(s *spec3.OpenAPI) {
	if s.Components == nil || s.Components.Schemas == nil {
		return
	}

	for _, schema := range s.Components.Schemas {
		processSchemaDefaults(schema)
	}
}

func processSchemaDefaults(schema *spec.Schema) {
	// Look for x-kubernetes-group-version-kind extension
	rawExt, ok := schema.Extensions["x-kubernetes-group-version-kind"]
	if !ok {
		return
	}

	// Convert the extension to a usable format
	gvkList := extractGVKList(rawExt)
	if len(gvkList) == 0 {
		return
	}

	// Extract group, version, and kind from the first GVK
	group, version, kind := extractGVKInfo(gvkList[0])

	// Construct apiVersion
	apiVersion := constructAPIVersion(group, version)

	// Add defaults to properties
	addSchemaPropertyDefaultsGo(schema, apiVersion, kind)
}

func extractGVKList(rawExt any) []map[string]any {
	var gvkList []map[string]any
	switch ext := rawExt.(type) {
	case []any:
		for _, item := range ext {
			if gvk, ok := item.(map[string]any); ok {
				gvkList = append(gvkList, gvk)
			}
		}
	case []map[string]any:
		gvkList = ext
	}
	return gvkList
}

func extractGVKInfo(gvk map[string]any) (group, version, kind string) {
	if g, ok := gvk["group"].(string); ok {
		group = g
	}
	if v, ok := gvk["version"].(string); ok {
		version = v
	}
	if k, ok := gvk["kind"].(string); ok {
		kind = k
	}
	return group, version, kind
}

func constructAPIVersion(group, version string) string {
	if group != "" {
		return group + "/" + version
	}
	return version
}

func addSchemaPropertyDefaultsGo(schema *spec.Schema, apiVersion, kind string) {
	if schema.Properties == nil {
		return
	}

	// Add default to apiVersion property
	if propSchema, ok := schema.Properties["apiVersion"]; ok {
		propSchema.Default = apiVersion
		propSchema.Enum = []any{apiVersion}
		schema.Properties["apiVersion"] = propSchema
	}

	// Add default to kind property
	if propSchema, ok := schema.Properties["kind"]; ok {
		propSchema.Default = kind
		propSchema.Enum = []any{kind}
		schema.Properties["kind"] = propSchema
	}
}

// removeSelfImports removes self-imports and removes
// the package prefix from types that would use the self-import.
func removeSelfImports(code string, pkg string) (string, error) {
	selfImports := map[string]struct {
		Alias, Path string
	}{
		k8sPkgMetaV1:        {"metacorev1", "dev.crossplane.io/models/io/k8s/core/meta/v1"},
		k8sPkgCoreV1:        {"corev1", "dev.crossplane.io/models/io/k8s/core/v1"},
		k8sPkgRuntime:       {"runtimev1", "dev.crossplane.io/models/io/k8s/runtime/v1"},
		k8sPkgIntStr:        {"intstrv1", "dev.crossplane.io/models/io/k8s/util/v1"},
		k8sPkgResource:      {"resourcev1", "dev.crossplane.io/models/io/k8s/resource/v1"},
		k8sPkgAutoscalingV1: {"autoscalingv1", "dev.crossplane.io/models/io/k8s/autoscaling/v1"},
	}

	info, ok := selfImports[pkg]
	if !ok {
		return code, nil // nothing to strip
	}

	// parse
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		return "", errors.Wrap(err, "parsing Go code")
	}

	// delete the import (works for both named & unnamed imports)
	astutil.DeleteImport(fset, f, info.Path)
	astutil.DeleteNamedImport(fset, f, info.Alias, info.Path)

	// strip selectors: transform `alias.Thing` → `Thing`
	astutil.Apply(f, nil, func(c *astutil.Cursor) bool {
		if sel, ok := c.Node().(*ast.SelectorExpr); ok {
			if pkgIdent, ok := sel.X.(*ast.Ident); ok && pkgIdent.Name == info.Alias {
				// replace the selector expr with just the identifier
				c.Replace(&ast.Ident{Name: sel.Sel.Name, NamePos: sel.Sel.NamePos})
			}
		}
		return true
	})

	var buf strings.Builder
	if err := format.Node(&buf, fset, f); err != nil {
		return "", errors.Wrap(err, "formatting Go code")
	}
	return buf.String(), nil
}

// fixMissingImports add missing imports for K8s types.
func fixMissingImports(code string) (string, error) {
	// 1. Define the k8s imports you might need
	k8sImports := map[string]string{
		"metacorev1":    "dev.crossplane.io/models/io/k8s/core/meta/v1",
		"metav1":        "dev.crossplane.io/models/io/k8s/meta/v1",
		"corev1":        "dev.crossplane.io/models/io/k8s/core/v1",
		"resourcev1":    "dev.crossplane.io/models/io/k8s/resource/v1",
		"runtimev1":     "dev.crossplane.io/models/io/k8s/runtime/v1",
		"intstrv1":      "dev.crossplane.io/models/io/k8s/util/v1",
		"autoscalingv1": "dev.crossplane.io/models/io/k8s/autoscaling/v1",
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		return "", errors.Wrap(err, "parsing failed")
	}

	needed := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if pkg, ok := sel.X.(*ast.Ident); ok {
				if _, known := k8sImports[pkg.Name]; known {
					needed[pkg.Name] = true
				}
			}
		}
		return true
	})

	for alias, path := range k8sImports {
		if !needed[alias] {
			continue
		}
		// AddNamedImport will do nothing if the import (with that alias) is already present
		astutil.AddNamedImport(fset, f, alias, path)
	}

	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, f); err != nil {
		return "", errors.Wrap(err, "printing AST failed")
	}
	return buf.String(), nil
}

// fixK8sTypeNames uses AST manipulation to replace long K8s type names with short ones.
func fixK8sTypeNames(code string) (string, error) {
	// Parse the code
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse Go code")
	}

	replacements := map[string]string{
		// Types that map to time.Time.
		"IoK8SApimachineryPkgApisMetaV1Time":      "Time",
		"IoK8SApimachineryPkgApisMetaV1MicroTime": "MicroTime",
		// Union types from IntOrString and their related methods.
		"IoK8SApimachineryPkgUtilIntstrIntOrString0":      "Int",
		"FromIoK8SApimachineryPkgUtilIntstrIntOrString0":  "FromInt",
		"AsIoK8SApimachineryPkgUtilIntstrIntOrString0":    "AsInt",
		"MergeIoK8SApimachineryPkgUtilIntstrIntOrString0": "MergeInt",
		"IoK8SApimachineryPkgUtilIntstrIntOrString1":      "String",
		"FromIoK8SApimachineryPkgUtilIntstrIntOrString1":  "FromString",
		"AsIoK8SApimachineryPkgUtilIntstrIntOrString1":    "AsString",
		"MergeIoK8SApimachineryPkgUtilIntstrIntOrString1": "MergeString",
	}

	// Walk the AST and replace type names
	ast.Inspect(f, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			if newName, ok := replacements[x.Name]; ok {
				x.Name = newName
			}
		}
		return true
	})

	// Format and return the modified code
	var buf strings.Builder
	if err := format.Node(&buf, fset, f); err != nil {
		return "", errors.Wrap(err, "failed to format Go code")
	}

	return buf.String(), nil
}

// GenerateFromOpenAPI generates Go schemas for the OpenAPI docs in the given filesystem.
func (goGenerator) GenerateFromOpenAPI(_ context.Context, fromFS afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	// Walk through filesystem to collect OpenAPI specs
	openAPISpecs, err := collectOpenAPISpecs(fromFS)
	if err != nil {
		return nil, err
	}

	if len(openAPISpecs) == 0 {
		// Return nil if no specs were generated
		return nil, nil
	}

	// Initialize the schema filesystem
	schemaFS, err := initializeSchemaFS()
	if err != nil {
		return nil, err
	}

	// Generate K8s shared schemas
	if err := generateK8sSharedSchemas(openAPISpecs, schemaFS); err != nil {
		return nil, err
	}

	// Generate models for the rest
	if err := generateModelsWithGVK(openAPISpecs, schemaFS); err != nil {
		return nil, err
	}

	return schemaFS, nil
}

// collectOpenAPISpecs walks through the filesystem to find and parse OpenAPI JSON files.
func collectOpenAPISpecs(fromFS afero.Fs) ([]*spec3.OpenAPI, error) {
	var openAPISpecs []*spec3.OpenAPI

	err := afero.Walk(fromFS, "", func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		// Only process JSON files
		if !strings.HasSuffix(strings.ToLower(path), ".json") {
			return nil
		}

		// Read the file content
		bs, err := afero.ReadFile(fromFS, path)
		if err != nil {
			return errors.Wrapf(err, "failed to read file %q", path)
		}

		// Parse as OpenAPI spec
		var spec spec3.OpenAPI
		if err := json.Unmarshal(bs, &spec); err != nil {
			// Skip files that aren't valid OpenAPI specs
			return nil //nolint:nilerr // See comment above.
		}

		// Check if it has components/schemas
		if spec.Components == nil || len(spec.Components.Schemas) == 0 {
			return nil
		}

		openAPISpecs = append(openAPISpecs, &spec)
		return nil
	})

	return openAPISpecs, err
}

// initializeSchemaFS creates and initializes the schema filesystem with go.mod and go.sum.
func initializeSchemaFS() (afero.Fs, error) {
	schemaFS := afero.NewMemMapFs()
	if err := schemaFS.Mkdir("models", 0o755); err != nil {
		return nil, errors.Wrap(err, "failed to create models directory")
	}

	modf, err := schemaFS.Create("models/go.mod")
	if err != nil {
		return nil, errors.Wrap(err, "failed to create go.mod")
	}
	if _, err := modf.WriteString(goModContents); err != nil {
		return nil, errors.Wrap(err, "failed to write go.mod")
	}

	sumf, err := schemaFS.Create("models/go.sum")
	if err != nil {
		return nil, errors.Wrap(err, "failed to create go.sum")
	}
	if _, err := sumf.WriteString(goSumContents); err != nil {
		return nil, errors.Wrap(err, "failed to write go.sum")
	}

	return schemaFS, nil
}

// generateK8sSharedSchemas extracts and generates shared K8s schemas.
func generateK8sSharedSchemas(openAPISpecs []*spec3.OpenAPI, schemaFS afero.Fs) error {
	k8sSchemasByPackage := make(map[string]map[string]*spec.Schema)

	// Collect all K8s schemas from all OpenAPI specs, grouped by package
	for _, openAPISpec := range openAPISpecs {
		packagedSchemas := goExtractK8sSchemas(openAPISpec)
		for pkg, schemas := range packagedSchemas {
			if k8sSchemasByPackage[pkg] == nil {
				k8sSchemasByPackage[pkg] = make(map[string]*spec.Schema)
			}
			maps.Copy(k8sSchemasByPackage[pkg], schemas)
		}
	}

	// Generate separate files for each K8s package
	for pkg, schemas := range k8sSchemasByPackage {
		if len(schemas) == 0 {
			continue
		}

		if err := generateK8sPackageCode(pkg, schemas, schemaFS); err != nil {
			return err
		}
	}

	return nil
}

// generateK8sPackageCode generates code for a single K8s package.
func generateK8sPackageCode(pkg string, schemas map[string]*spec.Schema, schemaFS afero.Fs) error {
	// Create a spec for this package
	pkgSpec := &spec3.OpenAPI{
		Version: "3.0.0",
		Components: &spec3.Components{
			Schemas: schemas,
		},
	}

	// Determine the group, kind, and version from the package name
	group, kind, version := getK8sPackageInfo(pkg)

	code, err := generateGo(pkgSpec, version,
		goRenameTypes,
		goRenameEnums,
		goReplaceNumberWithInt,
		goRemoveRequired,
		goReferenceK8sTypes,
		goAddDefaults,
	)
	if err != nil {
		return err
	}

	// Fix k8s type names to use short names
	code, err = fixK8sTypeNames(code)
	if err != nil {
		return errors.Wrap(err, "failed to fix K8s type names")
	}
	// Remove self-imports from k8s packages
	code, err = removeSelfImports(code, pkg)
	if err != nil {
		return errors.Wrap(err, "failed to remove self imports")
	}

	return writeGoCode(schemaFS, group, kind, version, code)
}

// getK8sPackageInfo returns group, kind, and version for a K8s package.
func getK8sPackageInfo(pkg string) (group, kind, version string) {
	switch pkg {
	case k8sPkgMetaV1:
		return "meta.core.k8s.io", "meta", "v1"
	case k8sPkgRuntime:
		return "runtime.k8s.io", "runtime", "v1"
	case k8sPkgCoreV1:
		return "core.k8s.io", "core", "v1"
	case k8sPkgIntStr:
		return "util.k8s.io", "intstr", "v1"
	case k8sPkgResource:
		return "resource.k8s.io", "resource", "v1"
	case k8sPkgAutoscalingV1:
		return k8sPkgNameAutoscaling, k8sPkgNameAutoscaling, "v1"
	default:
		return "", "", ""
	}
}

// generateModelsWithGVK generates models for schemas with GVK information.
func generateModelsWithGVK(openAPISpecs []*spec3.OpenAPI, schemaFS afero.Fs) error {
	for _, openAPISpec := range openAPISpecs {
		gvkGroups := groupSchemasByGVK(openAPISpec)

		for gvkKey, schemas := range gvkGroups {
			if err := generateGVKGroupCode(gvkKey, schemas, openAPISpec, schemaFS); err != nil {
				return err
			}
		}
	}
	return nil
}

// groupSchemasByGVK groups schemas by their GVK information.
func groupSchemasByGVK(openAPISpec *spec3.OpenAPI) map[string]map[string]*spec.Schema {
	gvkGroups := make(map[string]map[string]*spec.Schema)

	for name, schema := range openAPISpec.Components.Schemas {
		gvkKey := extractGVKKey(schema)
		if gvkKey == "" {
			continue
		}

		if gvkGroups[gvkKey] == nil {
			gvkGroups[gvkKey] = make(map[string]*spec.Schema)
		}
		gvkGroups[gvkKey][name] = schema
	}

	return gvkGroups
}

// extractGVKKey extracts the GVK key from a schema's extensions.
func extractGVKKey(schema *spec.Schema) string {
	gvkExt, ok := schema.Extensions["x-kubernetes-group-version-kind"]
	if !ok {
		return ""
	}

	gvkList, ok := gvkExt.([]any)
	if !ok || len(gvkList) == 0 {
		return ""
	}

	gvk, ok := gvkList[0].(map[string]any)
	if !ok {
		return ""
	}

	group, ok := gvk["group"].(string)
	if !ok {
		return ""
	}

	version, ok := gvk["version"].(string)
	if !ok || version == "" {
		return ""
	}

	// Skip core group as it's already created upfront
	if group == "core" || group == "" {
		return ""
	}

	return group + "/" + version
}

// generateGVKGroupCode generates code for a GVK group.
func generateGVKGroupCode(gvkKey string, schemas map[string]*spec.Schema, openAPISpec *spec3.OpenAPI, schemaFS afero.Fs) error {
	parts := strings.Split(gvkKey, "/")
	group, version := parts[0], parts[1]

	// Extract the kind from the group name for file naming
	// For groups like "authentication.k8s.io", use "authentication" as the kind
	// For groups like "policy", use "policy" as the kind
	kind := group
	if before, _, ok := strings.Cut(group, "."); ok {
		kind = before
	}

	groupSpec := &spec3.OpenAPI{
		Version: "3.0.0",
		Components: &spec3.Components{
			Schemas: make(map[string]*spec.Schema),
		},
	}

	// Add the main schemas for this GVK group
	maps.Copy(groupSpec.Components.Schemas, schemas)

	// Add all other schemas from the same spec that might be referenced
	// but don't have GVK extensions (like TokenRequestSpec, etc.)
	// Add schemas that don't have GVK extensions (supporting types)
	maps.Copy(groupSpec.Components.Schemas, openAPISpec.Components.Schemas)

	code, err := generateGo(groupSpec, version,
		goRenameTypes,
		goRenameEnums,
		goReplaceNumberWithInt,
		goRemoveRequired,
		goReferenceK8sTypes,
		goRemoveK8s,
		goKeepOnlyComponents,
		goAddDefaults,
	)
	if err != nil {
		return err
	}

	return writeGoCode(schemaFS, group, kind, version, code)
}
